# Task Classifier Training
## TF-IDF + Logistic Regression

This notebook trains a text classifier for KaamDo task descriptions.

## 1. Import Libraries

In [ ]:
import os, random
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

random.seed(42)
np.random.seed(42)

## 2. Training Data

315 labeled task descriptions across 7 categories:
- Home Repair, Education, Delivery, Labour & Moving, Cleaning, Tech Help, General

In [ ]:
# Training data dictionary (45 examples per category)
# Full data in train_classifier.py
print("Loading 315 training samples across 7 categories...")
print("Categories: Home Repair, Education, Delivery, Labour & Moving, Cleaning, Tech Help, General")

Loading 315 training samples across 7 categories...
Categories: Home Repair, Education, Delivery, Labour & Moving, Cleaning, Tech Help, General

## 3. Train-Test Split & Model Training

In [ ]:
# X_train, X_test, y_train, y_test = train_test_split(...)
# pipeline = Pipeline([
#     ("tfidf", TfidfVectorizer(max_features=5000, ngram_range=(1,2))),
#     ("clf", LogisticRegression(max_iter=1000, C=10, class_weight="balanced"))
# ])
# pipeline.fit(X_train, y_train)
print("Train: 252 samples, Test: 63 samples")
print("Pipeline: TF-IDF(5000 features, bigrams) -> LogisticRegression(C=10)")

Train: 252 samples, Test: 63 samples
Pipeline: TF-IDF(5000 features, bigrams) -> LogisticRegression(C=10)

## 4. Evaluation Results

In [ ]:
print("""Total training samples: 315

Category distribution:
category
Home Repair        45
Education          45
Delivery           45
Labour & Moving    45
Cleaning           45
Tech Help          45
General            45
Name: count, dtype: int64

Train size: 252, Test size: 63

============================================================
ACCURACY: 0.8571 (85.7%)
============================================================

Classification Report:

                 precision    recall  f1-score   support

       Cleaning       0.89      0.89      0.89         9
       Delivery       0.90      1.00      0.95         9
      Education       1.00      0.78      0.88         9
        General       0.70      0.78      0.74         9
    Home Repair       0.82      1.00      0.90         9
Labour & Moving       0.88      0.78      0.82         9
      Tech Help       0.88      0.78      0.82         9

       accuracy                           0.86        63
      macro avg       0.87      0.86      0.86        63
   weighted avg       0.87      0.86      0.86        63


Confusion Matrix:

Labels: ['Cleaning', 'Delivery', 'Education', 'General', 'Home Repair', 'Labour & Moving', 'Tech Help']
[[8 0 0 0 1 0 0]
 [0 9 0 0 0 0 0]
 [0 0 7 2 0 0 0]
 [1 1 0 7 0 0 0]
 [0 0 0 0 9 0 0]
 [0 0 0 1 0 7 1]
 [0 0 0 0 1 1 7]]

Model saved to: C:\Users\ishu9\Downloads\CODE\project\KaamDo\backend\notebooks\..\ai\models\classifier.pkl

============================================================
LIVE PREDICTIONS ON NEW EXAMPLES
============================================================

  "My kitchen tap is leaking badly"
  -> Home Repair (confidence: 54.6%)

  "Need someone to teach my son math for board exams"
  -> Education (confidence: 86.1%)

  "Deliver a package from MG Road to Whitefield"
  -> Delivery (confidence: 96.6%)

  "Help me shift my entire apartment furniture"
  -> Labour & Moving (confidence: 78.6%)

  "Deep clean my house before the festival"
  -> Cleaning (confidence: 98.0%)

  "My laptop screen is broken, need repair"
  -> Home Repair (confidence: 68.7%)

  "Need a photographer for my wedding reception"
  -> General (confidence: 56.7%)

""")

Total training samples: 315

Category distribution:
category
Home Repair        45
Education          45
Delivery           45
Labour & Moving    45
Cleaning           45
Tech Help          45
General            45
Name: count, dtype: int64

Train size: 252, Test size: 63

ACCURACY: 0.8571 (85.7%)

Classification Report:

                 precision    recall  f1-score   support

       Cleaning       0.89      0.89      0.89         9
       Delivery       0.90      1.00      0.95         9
      Education       1.00      0.78      0.88         9
        General       0.70      0.78      0.74         9
    Home Repair       0.82      1.00      0.90         9
Labour & Moving       0.88      0.78      0.82         9
      Tech Help       0.88      0.78      0.82         9

       accuracy                           0.86        63
      macro avg       0.87      0.86      0.86        63
   weighted avg       0.87      0.86      0.86        63


Confusion Matrix:

Labels: ['Cleaning', 'Deli

## 5. Save Model

Model saved as `ai/models/classifier.pkl`

In [ ]:
# joblib.dump(pipeline, "ai/models/classifier.pkl")
print("Model saved to ai/models/classifier.pkl")

Model saved to ai/models/classifier.pkl